## 01NVb-003-072
participant_directory: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-072'
preprocessed_datasets_path: '/home/mx19/datasets/vital-us/echocardiography/preprocessed-datasets'
video_output_pathname: 'cropped_us_image'
participant_path_json_file: '/home/mx19/datasets/vital-us/echocardiography/json/01NVb-003-072'
bounds:
  start_x: 480
  start_y: 120
  width: 1130
  height: 810
