## 01NVb-003-072/T1
#videofile_in: '/home/mx19/datasets/vital-us/echocardiography/videos/01NVb-003-072/T1/01NVb-003-072-1-echo.mp4'
#image_frames_path: '/home/mx19/datasets/vital-us/echocardiography/preprocessed-datasets/01NVb-003-072/T1/cropped_us_image'
#path_with_json_file: '/home/mx19/datasets/vital-us/echocardiography/json/01NVb-003-072/01NVb_003_072_T1_4CV.json'
#bounds:
#  start_x: 480
#  start_y: 120
#  width: 1130
#  height: 810

## 01NVb-003-072/T2
#videofile_in: '/home/mx19/datasets/vital-us/echocardiography/videos/01NVb-003-072/T2/01NVb-003-072-2-echo-cont.mp4'
#image_frames_path: '/home/mx19/datasets/vital-us/echocardiography/preprocessed-datasets/01NVb-003-072/T2/cropped_us_image'
#path_with_json_file: '/home/mx19/datasets/vital-us/echocardiography/json/01NVb-003-072/01NVb_003_072_T2_4CV.json'
#bounds:
#  start_x: 480
#  start_y: 120
#  width: 1130
#  height: 810

# 01NVb-003-072/T3
videofile_in: '/home/mx19/datasets/vital-us/echocardiography/videos/01NVb-003-072/T3/01NVb-003-072-3-echo.mp4'
image_frames_path: '/home/mx19/datasets/vital-us/echocardiography/preprocessed-datasets/01NVb-003-072/T3/cropped_us_image'
path_with_json_file: '/home/mx19/datasets/vital-us/echocardiography/json/01NVb-003-072/01NVb_003_072_T3_4CV.json'
bounds:
  start_x: 480
  start_y: 120
  width: 1130
  height: 810
