## 01NVb-003-070
participant_directory: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-070'
preprocessed_datasets_path: '/home/mx19/datasets/vital-us/echocardiography/preprocessed-datasets'
video_output_pathname: 'cropped_us_image'
participant_path_json_file: '/home/mx19/repositories/echocardiography/datasets/labelling-annotation/json_files/4CV/01NVb_003_070'
bounds:
  start_x: 480
  start_y: 120
  width: 1130
  height: 810

### 01NVb-003-071
#participant_directory: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-071'
#preprocessed_datasets_path: '/home/mx19/datasets/vital-us/echocardiography/preprocessed-datasets'
#video_output_pathname: 'cropped_us_image'
#participant_path_json_file: '/home/mx19/repositories/echocardiography/datasets/labelling-annotation/json_files/4CV/01NVb_003_071'
#bounds:
#  start_x: 480
#  start_y: 120
#  width: 1130
#  height: 810


### 01NVb-003-072
#participant_directory: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-072'
#preprocessed_datasets_path: '/home/mx19/datasets/vital-us/echocardiography/preprocessed-datasets'
#video_output_pathname: 'cropped_us_image'
##participant_path_json_file: '/home/mx19/datasets/vital-us/echocardiography/json/01NVb-003-072'
#participant_path_json_file: '/home/mx19/repositories/echocardiography/datasets/labelling-annotation/json_files/4CV/01NVb_003_072'
#bounds:
#  start_x: 480
#  start_y: 120
#  width: 1130
#  height: 810

### 01NVb-003-073
#participant_directory: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-073'
#preprocessed_datasets_path: '/home/mx19/datasets/vital-us/echocardiography/preprocessed-datasets'
#video_output_pathname: 'cropped_us_image'
#participant_path_json_file: '/home/mx19/repositories/echocardiography/datasets/labelling-annotation/json_files/4CV/01NVb_003_073'
#bounds:
#  start_x: 480
#  start_y: 120
#  width: 1130
#  height: 810

### 01NVb-003-074
#participant_directory: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-074'
#preprocessed_datasets_path: '/home/mx19/datasets/vital-us/echocardiography/preprocessed-datasets'
#video_output_pathname: 'cropped_us_image'
#participant_path_json_file: '/home/mx19/repositories/echocardiography/datasets/labelling-annotation/json_files/4CV/01NVb_003_074'
#bounds:
#  start_x: 480
#  start_y: 120
#  width: 1130
#  height: 810

### 01NVb-003-075
#participant_directory: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-075'
#preprocessed_datasets_path: '/home/mx19/datasets/vital-us/echocardiography/preprocessed-datasets'
#video_output_pathname: 'cropped_us_image'
#participant_path_json_file: '/home/mx19/repositories/echocardiography/datasets/labelling-annotation/json_files/4CV/01NVb_003_075'
#bounds:
#  start_x: 480
#  start_y: 120
#  width: 1130
#  height: 810


### 01NVb-003-076
#participant_directory: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-076'
#preprocessed_datasets_path: '/home/mx19/datasets/vital-us/echocardiography/preprocessed-datasets'
#video_output_pathname: 'cropped_us_image'
#participant_path_json_file: '/home/mx19/repositories/echocardiography/datasets/labelling-annotation/json_files/4CV/01NVb_003_076'
#bounds:
#  start_x: 480
#  start_y: 120
#  width: 1130
#  height: 810

### 01NVb-003-077
#participant_directory: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-077'
#preprocessed_datasets_path: '/home/mx19/datasets/vital-us/echocardiography/preprocessed-datasets'
#video_output_pathname: 'cropped_us_image'
#participant_path_json_file: '/home/mx19/repositories/echocardiography/datasets/labelling-annotation/json_files/4CV/01NVb_003_077'
#bounds:
#  start_x: 480
#  start_y: 120
#  width: 1130
#  height: 810

#
### 01NVb-003-078
#participant_directory: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-078'
#preprocessed_datasets_path: '/home/mx19/datasets/vital-us/echocardiography/preprocessed-datasets'
#video_output_pathname: 'cropped_us_image'
#participant_path_json_file: '/home/mx19/repositories/echocardiography/datasets/labelling-annotation/json_files/4CV/01NVb_003_078'
#bounds:
#  start_x: 480
#  start_y: 120
#  width: 1130
#  height: 810

### 01NVb-003-079
#participant_directory: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-079'
#preprocessed_datasets_path: '/home/mx19/datasets/vital-us/echocardiography/preprocessed-datasets'
#video_output_pathname: 'cropped_us_image'
#participant_path_json_file: '/home/mx19/repositories/echocardiography/datasets/labelling-annotation/json_files/4CV/01NVb_003_079'
#bounds:
#  start_x: 480
#  start_y: 120
#  width: 1130
#  height: 810
#
### 01NVb-003-080
#participant_directory: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-080'
#preprocessed_datasets_path: '/home/mx19/datasets/vital-us/echocardiography/preprocessed-datasets'
#video_output_pathname: 'cropped_us_image'
#participant_path_json_file: '/home/mx19/repositories/echocardiography/datasets/labelling-annotation/json_files/4CV/01NVb_003_080'
#bounds:
#  start_x: 480
#  start_y: 120
#  width: 1130
#  height: 810
#
#
### 01NVb-003-081
#participant_directory: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-081'
#preprocessed_datasets_path: '/home/mx19/datasets/vital-us/echocardiography/preprocessed-datasets'
#video_output_pathname: 'cropped_us_image'
#participant_path_json_file: '/home/mx19/repositories/echocardiography/datasets/labelling-annotation/json_files/4CV/01NVb_003_081'
#bounds:
#  start_x: 480
#  start_y: 120
#  width: 1130
#  height: 810
#
