### US Device 
us_device_brand:  'GE'
model: 'Venue Go'
software_version: 'R2'
Transducers: 'Convex probe C1-5-D'

## Image bounds
## Capture Videos have the following features: frame_width=1920, frame_height=1080, fps=29.971...
crop_bounds_for_us_image:
  start_x: 480
  start_y: 120
  width: 1130
  height: 810

## Size to which the cropped area is resized to.
use_pretransform_image_size: True
pretransform_im_size:  !!python/tuple [128, 128] #[width, height]

## number of frames per clip
number_of_frames_per_segment_in_a_clip: 60
sliding_window_length_in_percentage_of_frames_per_segment: !!float 0.0

## Max duration of background clips
max_background_duration_in_secs: 5

## Training parameters
use_train_augmentation: True
use_validation_augmentation: True
batch_size: 20
max_epochs: 3

## Video paths
#main_data_path: '/home/ag09/data/VITAL/echo'
#participant_videos_list: '/home/ag09/data/VITAL/echo/video_list_train.txt'
#participant_path_json_list: '/home/ag09/data/VITAL/echo/annotation_list_train.txt'

## Video paths
user_path: &HOME_DIR '/home/mx19'
main_data_path: !join [*HOME_DIR, '/datasets/vital-us/echocardiography/videos-echo-annotated']
participant_videos_list_train: !join [*HOME_DIR, '/repositories/echocardiography/scripts/config_files/data_lists/video_list_train.txt']
participant_path_json_list_train: !join [*HOME_DIR, '/repositories/echocardiography/scripts/config_files/data_lists/annotation_list_train.txt']
participant_videos_list_validation: !join [*HOME_DIR, '/repositories/echocardiography/scripts/config_files/data_lists/video_list_validate.txt']
participant_path_json_list_validation: !join [*HOME_DIR, '/repositories/echocardiography/scripts/config_files/data_lists/annotation_list_validate.txt']

