### US Device 
us_device_brand:  'GE'
model: 'Venue Go'
software_version: 'R2'
Transducers: 'Convex probe C1-5-D'

### Datapaths
###### 01NVb-003-072
#participant_videos_path: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-072'
#participant_path_json_files: '/home/mx19/repositories/echocardiography/source/labelling-annotation/json_files/4CV/01NVb_003_072'

##### 01NVb-003-073
#participant_videos_path: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-073'
#participant_path_json_files: '/home/mx19/repositories/echocardiography/source/labelling-annotation/json_files/4CV/01NVb_003_073'

#### 01NVb-003-074
participant_videos_path: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-074'
participant_path_json_files: '/home/mx19/repositories/echocardiography/source/labelling-annotation/json_files/4CV/01NVb_003_074'

### Settings for Learning
learning:
  batchsize: 200


