### US Device 
us_device_brand:  'GE'
model: 'Venue Go'
software_version: 'R2'
Transducers: 'Convex probe C1-5-D'

### Setting Data Paths
#### USAGE: Comment or uncomment relevant lines for a given participant

###### 01NVb-003-060
##### p060 - T1-01clips; T2-00clips; T3-00clips
#participant_videos_path: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-060'
#participant_path_json_files: '/home/mx19/repositories/echocardiography/data/labelling/json_files/4CV/01NVb_003_060'

###### 01NVb-003-061
##### p061 - T1-00clips; T2-00clips; T3-01clips
#participant_videos_path: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-061'
#participant_path_json_files: '/home/mx19/repositories/echocardiography/data/labelling/json_files/4CV/01NVb_003_061'

###### 01NVb-003-062 ##NODATA
##### p060 - T1-00clips; T2-00clips; T3-00clips
#participant_videos_path: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-062'
#participant_path_json_files: '/home/mx19/repositories/echocardiography/data/labelling/json_files/4CV/01NVb_003_062'

###### 01NVb-003-063
##### p063 - T1-02clips; T2-02clips; T3-01clips
#participant_videos_path: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-063'
#participant_path_json_files: '/home/mx19/repositories/echocardiography/data/labelling/json_files/4CV/01NVb_003_063'

###### 01NVb-003-064
##### p064 - T1-02clips; T2-03clips; T3-00clips
#participant_videos_path: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-064'
#participant_path_json_files: '/home/mx19/repositories/echocardiography/data/labelling/json_files/4CV/01NVb_003_064'

###### 01NVb-003-065
##### p065 - T1-02clips; T2-04clips; T3-05clips
#participant_videos_path: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-065'
#participant_path_json_files: '/home/mx19/repositories/echocardiography/data/labelling/json_files/4CV/01NVb_003_065'

###### 01NVb-003-066
##### p066 - T1-01clips; T2-02clips; T3-00clips
#participant_videos_path: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-066'
#participant_path_json_files: '/home/mx19/repositories/echocardiography/data/labelling/json_files/4CV/01NVb_003_066'

###### 01NVb-003-067 ##NO4CV
##### p067 - T1-00clips; T2-00clips; T3-00clips
#participant_videos_path: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-067'
#participant_path_json_files: '/home/mx19/repositories/echocardiography/data/labelling/json_files/4CV/01NVb_003_067'

###### 01NVb-003-068
##### p068 - T1-02clips; T2-00clips; T3-02clips
#participant_videos_path: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-068'
#participant_path_json_files: '/home/mx19/repositories/echocardiography/data/labelling/json_files/4CV/01NVb_003_068'

###### 01NVb-003-069
##### p069 - T1-02clips; T2-03clips; T3-02clips
#participant_videos_path: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-069'
#participant_path_json_files: '/home/mx19/repositories/echocardiography/data/labelling/json_files/4CV/01NVb_003_069'

###### 01NVb-003-070 ## CODEC ERRORS
###### 070 - T1-04clips; T2-04clips; T3-01clips
#participant_videos_path: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-070'
#participant_path_json_files: '/home/mx19/repositories/echocardiography/data/labelling/json_files/4CV/01NVb_003_070'

###### 01NVb-003-071 ## CODEC ERRORS
###### 071 - T1-00clips; T2-02clips; T3-01clips
#participant_videos_path: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-071'
#participant_path_json_files: '/home/mx19/repositories/echocardiography/data/labelling/json_files/4CV/01NVb_003_071'

##### 01NVb-003-072
##### 072 - T1-01clips; T2-03clips; T3-02clips
participant_videos_path: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-072'
participant_path_json_files: '/home/mx19/repositories/echocardiography/data/labelling/json_files/4CV/01NVb_003_072'

##### 01NVb-003-073
##### 073 - T1-02clips; T2-01clips; T3-00clips
#participant_videos_path: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-073'
#participant_path_json_files: '/home/mx19/repositories/echocardiography/data/labelling/json_files/4CV/01NVb_003_073'

##### 01NVb-003-074
##### 074 - T1-02clips; T2-02clips; T3-00clips
#participant_videos_path: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-074'
#participant_path_json_files: '/home/mx19/repositories/echocardiography/data/labelling/json_files/4CV/01NVb_003_074'

##### 01NVb-003-075
##### 075 - T1-01clips; T2-02clips; T3-02clips
#participant_videos_path: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-075'
#participant_path_json_files: '/home/mx19/repositories/echocardiography/data/labelling/json_files/4CV/01NVb_003_075'

##### 01NVb-003-076
##### 076 - T1-01clips; T2-01clips; T3-02clips
#participant_videos_path: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-076'
#participant_path_json_files: '/home/mx19/repositories/echocardiography/data/labelling/json_files/4CV/01NVb_003_076'

##### 01NVb-003-077 ##NO 4CV
##### 077 - T1-00clips; T2-00clips; T3-00clips
#participant_videos_path: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-077'
#participant_path_json_files: '/home/mx19/repositories/echocardiography/data/labelling/json_files/4CV/01NVb_003_077'

##### 01NVb-003-078
##### 078 - T1-01clips; T2-01clips; T3-01clips
#participant_videos_path: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-078'
#participant_path_json_files: '/home/mx19/repositories/echocardiography/data/labelling/json_files/4CV/01NVb_003_078'

##### 01NVb-003-079
##### 079 - T1-01clips; T2-02clips; T3-01clips
#participant_videos_path: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-079'
#participant_path_json_files: '/home/mx19/repositories/echocardiography/data/labelling/json_files/4CV/01NVb_003_079'

##### 01NVb-003-080 ## CODEC ERRORS
##### 080 - T1-00clips; T2-00clips; T3-00clips
#participant_videos_path: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-080'
#participant_path_json_files: '/home/mx19/repositories/echocardiography/data/labelling/json_files/4CV/01NVb_003_080'

##### 01NVb-003-081 ##NO 4CV
##### 081 - T1-00clips; T2-00clips; T3-00clips
#participant_videos_path: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-081'
#participant_path_json_files: '/home/mx19/repositories/echocardiography/data/labelling/json_files/4CV/01NVb_003_081'


### Settings for Learning
learning:
  batchsize: 200


