### US Device 
us_device:  'GE Venue Go'
model: '?'
software_version: '?'
Transducers: 'Convex probe C1-5-D'

### Datapaths
#### 01NVb-003-072
participant_videos_path: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-072'
participant_path_json_files: '/home/mx19/datasets/vital-us/echocardiography/json/01NVb-003-072'

### Settings for Learning
learning:
  batchsize: 200


