### US Device 
us_device:  '?'
model: '?'
software_version: '?'

### Datapaths
#### 01NVb-003-072
participant_datapath: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-072'
participant_path_json_files: '/home/mx19/datasets/vital-us/echocardiography/json/01NVb-003-072'
video_list_file: '/home/mx19/repositories/echocardiography/scripts/config_files/video_list.txt'
annotation_list_file: '/home/mx19/repositories/echocardiography/scripts/config_files/annotation_list.txt'


### Settings for Learning
learning:
  batchsize: 200


