### US Device 
us_device_brand:  'GE'
model: 'Venue Go'
software_version: 'R2'
Transducers: 'Convex probe C1-5-D'

## Image bounds
crop_bounds:
  start_x: 480
  start_y: 120
  width: 1130
  height: 810

## Video paths
participants_videos_path: '/home/mx19/datasets/vital-us/echocardiography/videos-echo'
participants_path_json_files: '/home/mx19/repositories/echocardiography/data/labelling/json_files/4CV'


###### 01NVb-003-060
##### p060 - T1-01clips; T2-00clips; T3-00clips
#participant_videos_path: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-060'
#participant_path_json_files: '/home/mx19/repositories/echocardiography/data/labelling/json_files/4CV/01NVb_003_060'

###### 01NVb-003-061
##### p061 - T1-00clips; T2-00clips; T3-01clips
#participant_videos_path: '/home/mx19/datasets/vital-us/echocardiography/videos-echo/01NVb-003-061'
#participant_path_json_files: '/home/mx19/repositories/echocardiography/data/labelling/json_files/4CV/01NVb_003_061'

